{{- range $key,$val := .Values.global.applications }}
{{- /*
in order to use tpl within a range, _and_ have the key/val available to sub-templates,
need to add some variables to the root context.
*/ -}}
{{- $_ := set $ "curAppName" (print $.Values.global.envName "-" $key) }}
{{- if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ required "A valid envName is required" $.Values.global.envName }}-{{ $key }}
spec:
  destination:
    namespace: {{ $val.destination.namespace | required (printf "No destination.namespace specified for %s" $key ) }}
    server: {{ .Values.global.default.app.destination.server | required (printf "No destination.server specified for %s" $key ) }}
{{- if $.Values.global.projectOverride }}
  project: {{ $.Values.global.projectOverride }}
{{- else }}
  project: {{ $.Values.global.envName }}-{{ $val.project | required (printf "No project specified for %s" $key ) }}
{{- end }}
  syncPolicy:
   syncOptions:
   - CreateNamespace=true
{{- if $val.enableAutoSync | default $.Values.global.default.app.enableAutoSync }}  
   automated:
    prune: {{ $val.autoSyncPrune | default $.Values.global.default.app.autoSyncPrune | default true }}          
{{- end }}
  source:
    path: {{ tpl $val.source.path $ }}
    repoURL: {{ $val.source.repoURL | required (printf "No source.repoURL specified for %s" $key ) }}
    targetRevision: {{ $val.source.targetRevision | default $.Values.global.default.app.source.targetRevision |  default "HEAD"  }}
{{- if $val.source.extraSourceFields }}
{{ tpl $val.source.extraSourceFields $ | indent 4 }}
{{- else if $.Values.global.default.app.source.extraSourceFields }}
{{ tpl $.Values.global.default.app.source.extraSourceFields $ | indent 4 }}
{{- end }}
{{- if $val.extraFields }}
{{ tpl $val.extraFields $ | indent 2 }}
{{- else if $.Values.global.default.app.extraFields }}
{{ tpl $.Values.global.default.app.extraFields $ | indent 2 }}
{{- end }}
{{- end }}
{{- end }}